// frontend-store/src/routes/(unauthed)/login/+page.svelte
<script lang="ts">
  import "$lib/css/components-css/buttons.css"
  import "$lib/css/components-css/icon.css"
  import "$lib/css/pages-css/1-login.css"

  import IconText from "$lib/components/IconText.svelte";

  import { InputTypes } from "$lib/components/InputPropsI";
  import { UserType } from "$lib/domain/user";
  import type { ValidationMessage } from "$lib/domain/user";
  import { userService } from "$lib/services/UserService";
  import { showError } from '$lib/domain/errorHandler'
  import ValidationField from "$lib/components/ValidationField.svelte";
  import { goto } from "$app/navigation";
  import { toasts } from '$lib/components/toast/toastStore'
  import Input from "$lib/components/Input.svelte";

  let errors: ValidationMessage[] = $state([])
  let toastLock: boolean = false

  const onSubmit = async (ev: SubmitEvent) => {
    ev.preventDefault() // cancela el comportamiento por defecto del navegador frente al evento del submit

    // ev.currentTarget: es el elemento que tiene asignado el event listener
    // as HTMLFormElement es un type assertion de TypeScript: le decís explícitamente al compilador “esto es un formulario”
    const form = ev.currentTarget as HTMLFormElement
    const formData = new FormData(form) // creo el formData
    
    // console.info((formData.get("email") ?? "").toString())
    // console.info((formData.get("password") ?? "").toString())

    const user = new UserType(
      "Default name",
      (formData.get("password") ?? "").toString(),
      (formData.get("email") ?? "").toString()
    )

    user.validate()

    if (user.errors.length > 0) {
      errors = [...user.errors]
      return errors
    }

    try {
      let validation = await userService.getUser(user.email, user.password)
      if (validation) goto ("/orders") // si devuelve Truthy redirige a orders, quiza se podria mejorar esto con token? 
      // else {
      //   errorMessages = ["Nombre de usuario y/o contraseña incorrecto/s"]
      //   if(!toastLock) {
      //     errorMessages.forEach((error) => {
      //       toasts.push(error, {type: 'error'})
      //     })
      //   }
      // }
    } catch (error) {
      toasts.push("Nombre de usuario y/o contraseña incorrecto/s", {type: 'error'})
      // showError("Error", error) // manejar el error de manera adecuada
    } finally {
      errors = [] // limpiar errores
    }
  }

  let errorMessages: string[] = $state([])

  // console.log(USERS_LIST_MOCK);
</script>

<section class="login-container">
  <main class="login-section">
    <!-- HEADER -->
    <IconText wrapperClass="header-section" />
    <!-- FORM -->
    <form class="form-container" id="form-login" onsubmit={onSubmit}>
      <!-- FORM FIELD -->
      <!-- Chequear estos for y type -->
      <fieldset form="form-login" class="form-field" name="login-user">
        <div class="form-group">
          <div class="input-wrapper">
            <Input
              label_text="Usuario*"
              label_for="email"
              input_type={InputTypes.Normal}
              value=""
              class="input-primary"
              type="email"
              placeholder="Usuario"
              id="input-id"
              name="email"
              tabindex={1}
            />
            <ValidationField errors={errors} field="email" />
          </div>

          <div class="input-wrapper">
            <Input
              label_text="Contraseña*"
              label_for="password"
              input_type={InputTypes.Hidden}
              value=""
              class="input-primary"
              id="password-id"
              name="password"
              tabindex={2}
            />
            <ValidationField errors={errors} field="password" />
          </div>
        </div>
      </fieldset>

      <!-- FORM ACTIONS -->
      <section class="form-actions">

        <button type="submit" class="btn btn-primary btn-login">
          Iniciar Sesión
        </button>
        <div class="register-section">
          <p>¿No tenes una cuenta?</p>
          <a href="/register" class="register-link">Registrate</a>
        </div>
      </section>
    </form>
  </main>
</section>

// frontend-user/src/pages/auth/Login.tsx
import { FormEvent, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { TextField } from '@mui/material'
import {Button} from '@mui/material'
import { CookingPot, } from 'phosphor-react'
import './login-register.css'
import { UserJSONLoginRequest, UserType } from '../../domain/user'
import { userService } from '../../services/UserService'
import { ValidationMessage } from '../../domain/validationMessage'
import ValidationField from '../../components/ValidationField/ValidationField'
import { getErrorMessage } from '../../domain/errorHandler'
import { Toast } from '../../components/Toast/ToastContainer'
import { useToast } from '../../components/Toast/useToast'
import { useOnInit } from '../../customHooks/useOnInit'

const Login = () => {
  const { toast, showToast } = useToast()
  const [user, setUser] = useState<UserJSONLoginRequest>({email: '', password: ''})
  const [errors, setErrors] = useState<Array<ValidationMessage>>([])
  
  const navigate = useNavigate()
  const location = useLocation()
  const from = location.state?.from?.pathname || '/'

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    const form = e.currentTarget as HTMLFormElement
    const formData = new FormData(form)

    const userLogin = new UserType(
      'nombre',
      'apellido',
      (formData.get('password') ?? '').toString(),
      (formData.get('email') ?? '').toString(),
    )

    userLogin.validate()

    if (userLogin.errors.length > 0) {
      setErrors(userLogin.errors)
      return errors
    }

    try {
      let validation = await userService.login(userLogin.email, userLogin.password)
      if (validation) {
        navigate(from, {replace: true}) // recordar la ruta “from” y volver tras login
      }
    } catch (error) {
      const errorMessage = getErrorMessage(error)
      showToast(errorMessage, 'error')
    } finally {
      setErrors([])
    }
  }

  const actualizar = (clave: keyof typeof user, valor: unknown) => {
    setUser({
      ...user,
      [clave]: valor
    })
  }

  useOnInit(() => {
    // console.log(location.state?.from?.pathname)
    if (location.state?.from?.pathname != '/' && location.state?.from?.pathname != undefined) showToast('Debe loguearse.', 'error')
  })
    
  return (
    <div className="main-container-login">
      <div className='header-logo'>
        <CookingPot weight='fill' className='cooking-pot-logo'></CookingPot>
        <h1>Algo que pedir</h1>
      </div>

      <form
        onSubmit={handleSubmit}
        id='login-form'
        className='auth-form'
      >
        <TextField
          id='email'
          label="Email*"
          type="email"
          name='email'
          value={user.email}
          onChange={(e) => actualizar('email', e.target.value)}
          error={!errors?.every(valMess => valMess.field != 'email')}
          slotProps={{ 
            input: {
              inputProps: {
                'data-testid': 'emailInput'
              },
            }, 
          }}
        />
        <ValidationField field='email' errors={errors} />

        <TextField
          id='password'
          label="Contraseña*"
          type="password"
          name='password'
          value={user.password}
          onChange={(e) => actualizar('password', e.target.value)}
          error={!errors?.every(valMess => valMess.field != 'password')}
          slotProps={{ 
            input: {
              inputProps: {
                'data-testid': 'passwordInput'
              },
            }, 
          }}
        />
        <ValidationField field='password' errors={errors} />

        <Button variant="contained" color="primary" 
          type="submit"
          className='auth-submit-btn'
          data-testid='iniciarBtn'
        >
          Iniciar sesión
        </Button>
      </form>

      <span>¿No tenes cuenta? <Link to={'/register'} className='auth-anchor'>Registrate</Link></span>

      <div id="toast-container">
        <Toast toast={toast} />
      </div>
    </div>
  )
}

export default Login
