// frontend-store/src/routes/(unauthed)/register/+page.svelte
<script lang="ts">
  import "$lib/css/components-css/buttons.css";
  import "$lib/css/components-css/icon.css";
  import "$lib/css/pages-css/1-login.css";
  import "$lib/css/pages-css/2-register.css";

  import IconText from "$lib/components/IconText.svelte";
  import { InputTypes } from "$lib/components/InputPropsI";
  import { UserType, ValidationMessage } from "$lib/domain/user";
  import { userService } from "$lib/services/UserService";
  import { goto } from "$app/navigation";
  import { showError } from "$lib/domain/errorHandler";
  import ValidationField from "$lib/components/ValidationField.svelte";
  import { toasts } from '$lib/components/toast/toastStore';
  import Input from "$lib/components/Input.svelte";

  let errors: ValidationMessage[] = $state([])
  let toastLock: boolean = false

  let registerMessageNoMatched: string = $state("");
  let successmessages: string[] = $state([]);

  const onSubmit = async (ev: SubmitEvent) => {
    ev.preventDefault() // cancela el comportamiento por defecto del navegador frente al evento del submit

    // ev.currentTarget: es el elemento que tiene asignado el event listener
    // as HTMLFormElement es un type assertion de TypeScript: le decís explícitamente al compilador “esto es un formulario”
    const form = ev.currentTarget as HTMLFormElement
    const formData = new FormData(form) // creo el formData

    const user = new UserType(
      (formData.get("name") ?? "").toString(),
      (formData.get("password") ?? "").toString(),
      (formData.get("email") ?? "").toString()
    )
    console.info(user)
    user.validate()

    if (user.errors.length > 0) {
      errors = [...user.errors]
      return errors
    }
    try {
      // await userService.alreadyRegisteredUsername(user.username)
      if (formData.get("password") == formData.get("password-retry")) {
        
        await userService.createUser(user)
        
        successmessages = ['Usuario generado con exito.',' Seras redirigido a la pagina de Ingreso']

        if(!toastLock) {
          successmessages.forEach((message) => {
            toasts.push(message, {type: 'success'})
          })
          toastLock = true
          setTimeout(releaseToast, 5000)
        }

        setTimeout(() => {
          goto("/")
        }, 2000)

      } else {
        // Cambiar a error de front
        registerMessageNoMatched = "Las contraseñas no coinciden"
        toasts.push(registerMessageNoMatched, {type: 'error'})
        setTimeout(() => {
          registerMessageNoMatched = ""
        }, 3000)
      }
      errors = [] // limpiar errores
    } catch (error) {
      toasts.push("Error al generar usuario", {type: 'error'})
      // Esto esta mal, hay que mostrar el error del back
      showError("Error al generar usuario", error)
    }
  }

  const releaseToast = () => {
    toastLock = false
  } 
</script>

<section class="login-container">
  <main class="login-section">
    <!-- HEADER -->
    <IconText title="Crea tu cuenta" wrapperClass="header-section" />

    <!-- FORM -->
    <form class="form-container" onsubmit={onSubmit}>
      <!-- FORM FIELD -->
      <fieldset form="form-login" class="form-field" name="login-user">
        <div class="form-group">
          <div class="input-wrapper">
            <Input
              label_text="Email*"
              label_for="email"
              input_type={InputTypes.Normal}
              value=""
              type= "email"
              placeholder= "Escribir"
              id= "register-email-id"
              class= "input-primary"
              name= "email"
              tabindex={1}
            />
            <ValidationField errors={errors} field="email" />
          </div>

          <div class="input-wrapper">
            <Input
              label_text="Nombre*"
              label_for="name"
              input_type={InputTypes.Normal}
              value=""
              placeholder= "Escribir"
              id= "register-name-id"
              class= "input-primary"
              name= "name"
              tabindex={2}
            />
            <ValidationField errors={errors} field="name" />
          </div>

          <div class="input-wrapper">
            <Input
              label_text="Contraseña*"
              label_for="password"
              input_type={InputTypes.Hidden}
              value=""
              id= "register-password-id"
              class= "input-primary"
              name= "password"
              tabindex={3}
            />
            <ValidationField errors={errors} field="password" />
        </div>

          <div class="input-wrapper">
            <Input
              label_text="Re-ingrese la contraseña*"
              label_for="register-password-retry"
              input_type={InputTypes.Hidden}
              value=""
              id= "register-password-retry-id"
              class= "input-primary"
              name= "password-retry"
              tabindex={4}
            />
            <ValidationField errors={errors} field="password"/>
          </div>

        </div>
      </fieldset>

      <!-- FORM ACTIONS -->
      <section class="form-actions">
        <button class="btn btn-primary btn-login" type="submit"
          >Registrarse</button
        >
        <div class="register-section">
          <p>¿Ya tenes una cuenta?</p>
          <a href="./" class="register-link">Inicia sesion</a>
        </div>
      </section>
    </form>
  </main>
</section>

// frontend-user/src/pages/auth/Register.tsx
import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { TextField } from '@mui/material'
import {Button} from '@mui/material'
import './login-register.css'
import { UserJSONRegisterRequest, UserType } from '../../domain/user'
import { userService } from '../../services/UserService'
import { ValidationMessage } from '../../domain/validationMessage'
import ValidationField from '../../components/ValidationField/ValidationField'
import { getErrorMessage } from '../../domain/errorHandler'
import { Toast } from '../../components/Toast/ToastContainer'
import { useToast } from '../../components/Toast/useToast'
import { CookingPot } from 'phosphor-react'

const Register = () => {
  const { toast, showToast } = useToast()
  
  const navigate = useNavigate()
  const [user, setUser] = useState<UserJSONRegisterRequest>({name:'', lastName: '', email: '', password: '', passwordRetry: ''})
  const [errors, setErrors] = useState<Array<ValidationMessage>>([])

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    const form = e.currentTarget as HTMLFormElement
    const formData = new FormData(form)

    const userRegister = new UserType(
      'nombre',
      'apellido',
      (formData.get('password') ?? '').toString(),
      (formData.get('email') ?? '').toString(),
    )

    userRegister.validate()
    // console.log(userRegister.errors)
    // console.log(userRegister)

    if (userRegister.errors.length > 0) {
      setErrors(userRegister.errors)
      return errors
    }

    try {
      if (formData.get('password') != formData.get('password-retry')) {
        showToast('Las contraseñas no coinciden.', 'error')
        return
      }
        await userService.createUser(userRegister)

        showToast('Usuario generado con exito. Seras redirigido a la pagina de Ingreso', 'success', 2000)
        setTimeout(() => {
          navigate('/login')
        }, 2000)
    } catch (error) {
      const errorMessage = getErrorMessage(error)
      showToast(errorMessage, 'error', 5000)
    } finally {
      setErrors([])
    }
  }

  const actualizar = (clave: keyof typeof user, valor: unknown) => {
    setUser({
      ...user,
      [clave]: valor
    })
  }
    
  return (
    <div className="main-container-login">
      <div className='header-logo'>
        <CookingPot weight='fill' className='cooking-pot-logo'></CookingPot>
        <h1>Crea tu cuenta</h1>
      </div>

      <form
        onSubmit={handleSubmit}
        id='register-form'
        className='auth-form'
      >
        <TextField
          id='email'
          label="Email*"
          type="email"
          name='email'
          value={user.email}
          onChange={(e) => actualizar('email', e.target.value)}
          error={!errors?.every(valMess => valMess.field != 'email')}
          slotProps={{ 
            input: {
              inputProps: {
                'data-testid': 'emailInput'
              },
            }, 
          }}
        />
        <ValidationField field='email' errors={errors} />

        <TextField
          id='password'
          label="Contraseña*"
          type="password"
          name='password'
          value={user.password}
          onChange={(e) => actualizar('password', e.target.value)}
          error={!errors?.every(valMess => valMess.field != 'password')}
          slotProps={{ 
            input: {
              inputProps: {
                'data-testid': 'passwordInput'
              },
            }, 
          }}
        />
        <ValidationField field='password' errors={errors} />

        <TextField
          id='password-retry'
          label="Re-ingrese la contraseña*"
          type="password"
          name='password-retry'
          value={user.passwordRetry}
          onChange={(e) => actualizar('passwordRetry', e.target.value)}
          error={!errors?.every(valMess => valMess.field != 'password')}
          slotProps={{ 
            input: {
              inputProps: {
                'data-testid': 'passwordRetryInput'
              },
            }, 
          }}
        />
        <ValidationField field='password' errors={errors} />


        <Button variant="contained" color="primary" 
          type="submit"
          className='auth-submit-btn'
          data-testid='registerBtn'
        >
          Registrarme
        </Button>
      </form>

          <span>Ya tengo cuenta. <Link to={'/login'} className='auth-anchor'>Iniciar Sesión</Link></span>

      <div id="toast-container">
        <Toast toast={toast} />
      </div>
    </div>
  )
}

export default Register
